Handle unique constraints
alan-turing-institute/sqlsynthgen pull request #111
Opened 2023-06-30 16:21 UTC by mhauru

Adds functionality to deal with unique constraints in the DB schema when using row generators (default or custom).

The new features come bundled with two refactors that were necessary/helpful when developing this:
* The generators in `ssg.py` used to be classes that were instantiated every time a new row was to be generated. They are now classes that are instantiated once when `ssg.py` is called, and then `__call__` is called for the instance when a new row is to be generated. So the generation logic moved from `__init__` to `__call__`.
* I renamed `ColumnGenerator` in `make.py`to `RowGenerator` because that's what the docs call it, and renamed some variables correspondingly.

The way this PR deals with unique constraints is as follows: There is a new class called `UniqueGenerator`, of which we create an instance for each unique constraint in the database. It can wrap around any row generator, and it calls this generator repeatedly until it gets a value that isn't already in the database, and then returns that value. There's logic in `make.py` to make sure that every row generator is wrapped in an appropriate instance `UniqueGenerator`, so that e.g. if there's a unique constraint called `uniq_a` on a column called `a`, then which ever row generator generates the values for `a` would be wrapped in the instance of `UniqueGenerator` for `uniq_a`.

The implementation can deal with multicolumn unique constraints and in principle with multiple constraints affecting one column, although the latter is untested. The one limitation we have is that if a single constraint is on multiple columns the values for all these columns need to come from the same row generator.

`UniqueGenerator` loads all the existing values from the database into a `set` to check against when creating new values. It does this loading when it is called the first time and then never talks to the database again, keeping the `set` in memory.

I see two significant imperfections to this implementation:
1. We call the row generators again and again until we find a unique value. This could be expensive for some generators (for most I think it's a trivial cost). I really don't see a way around this. In the general case of some user provided generator yielding values of some type to be written into some number of database columns, I can't see how we could get the generator to yield unique values other by just saying "try again" and hoping for the best.
2. We load all the existing keys from the destination DB into memory. For small amounts of generated synthetic data like we have so far this is fine, but it could become a problem. The other option would be to just try to do the `INSERT`, catch failures and retry. If conflicts are common this could be slow (talking to the DB has overheads), but in retrospect I wonder if I should have gone with that design to avoid the memory use. However, I'm not quite sure how the catch-and-retry approach would mesh with e.g. story generators, we would have to put in some logic for understanding exactly which values/columns caused the unique constraint failure and regenerate only those and it sounds complicated. This approach has the benefit that a `UniqueGenerator` is just another row generator that wraps an inner generator, the changes are transparent to `create.py` and things like story generators.

Closes #74

2023-07-03 06:54 UTC, cptanalatriste commented on sqlsynthgen/make.py
> +            row_gen_column_set = set(row_gen.variable_names)
Shall `row_gen_column_set` be instantiated within the outer loop?

2023-07-03 07:01 UTC, cptanalatriste commented on sqlsynthgen/unique_generator.py
> +    def __init__(self, columns: List[str], table_name: str, max_tries: int = 100):
Is `ssg.py.j2` passing values for the `max_tries` parameter?

2023-07-03 07:03 UTC, cptanalatriste commented on sqlsynthgen/unique_generator.py
> +        query_text = f"SELECT {','.join(self.column_names)} FROM {self.table_name}"
`ChatGPT` doesn't like format strings, due to SQL injection risks :P

2023-07-03 07:14 UTC, cptanalatriste commented on sqlsynthgen/make.py
> +            if len(row_gen.variable_names) == 1:
Is it possible to move the generation of `output_indices` to the `UniqueGenerator` module? I do believe it's better for this code to be closer to the logic that actually makes use of these values.

2023-07-03 07:22 UTC, cptanalatriste requested changes
It's a great feature, and the implementation it's really cool. I just added a few comments about minor details.

2023-07-04 17:17 UTC, mhauru commented on sqlsynthgen/make.py
> +            if len(row_gen.variable_names) == 1:
Good idea, done.

2023-07-04 17:17 UTC, mhauru commented on sqlsynthgen/unique_generator.py
> +        query_text = f"SELECT {','.join(self.column_names)} FROM {self.table_name}"
Turns out you can't make column or table names be query parameters. :(

2023-07-04 17:18 UTC, mhauru commented on sqlsynthgen/unique_generator.py
> +    def __init__(self, columns: List[str], table_name: str, max_tries: int = 100):
Changed it so that it now is, by adding a user-settable parameter to the config for `max_tries`.

2023-07-04 17:18 UTC, mhauru commented on sqlsynthgen/make.py
> +            row_gen_column_set = set(row_gen.variable_names)
Done

2023-07-05 12:10 UTC, cptanalatriste approved these changes
Looks good to me!

2023-07-05 12:15 UTC, merged

2023-07-05 17:39 UTC, Iain-S commented
This is a post-merge comment to agree with @cptanalatriste , this is a great feature to have and a very cool implementation.