Tutorial updates
alan-turing-institute/sqlsynthgen pull request #117
Opened 2023-07-13 15:52 UTC by Olajumoke01

Updated version of the airbnb tutorial with missing code and commands. I think all the code in the tutorial should be working now. I added comments to the ssg manual edit file, to make it clearer which lines were added.

2023-07-14 14:14 UTC, cptanalatriste commented on docs/source/tutorials/airbnb.rst
> +This will generate a file with the results of your sql queries from config.yaml and these results will be stored in the variable ``SRC_STATS``.
I would reword this. Something like: "With this command, the results of the query defined in `config.yaml` will be stored in the `src-stats.yaml` file. If you recreate the generators, stored in `ssg.py`, you can verify that the query results are exposed via the `SRC_STATS` variable.

2023-07-14 14:17 UTC, cptanalatriste commented on docs/source/tutorials/airbnb.rst
> +In this example ``user_age_provider``, the ``query_results`` argument represents the results of the ``age_stats`` query and returns a random age value.
Just for clarity, I would reword it like: "Within the function `user_age_provider`, defined in `airbnb_generators.py`, the ..."

2023-07-14 14:19 UTC, cptanalatriste commented on pyproject.toml
> +pre-commit = {version = "^3.3.3", extras = ["dev"]}
Why was this dependency added?

2023-07-14 14:20 UTC, cptanalatriste commented
@Olajumoke01 is looking good: I just made some minor suggestions. Also, if you still have them, it would be nice to add the complete `config.yaml` and `airbnb_generators.py` files to the tutorial.

2023-07-14 14:33 UTC, mhauru commented on pyproject.toml
> +pre-commit = {version = "^3.3.3", extras = ["dev"]}
I asked Olajumoke to add it because we use `pre-commit` checks and have a config file for it. This came up when I suggested that she run `pre-commit install`, but she needed to install pre-commit first. It's unrelated to any of the other changes in this PR, just came up at the same time.

2023-07-14 14:34 UTC, cptanalatriste requested changes
Some minor changes, that I flagged as comments.

2023-07-14 14:36 UTC, Iain-S commented on docs/source/tutorials/airbnb.rst
> +After editing the ``config.yaml`` file, you can run: ::
This all looks good to me. Out of curiosity, how (if at all) does this `::` method of code block differ from the kind we've been using? I.e.

```text
.. code-block::
```

Are they equivalent or is one better than the other?

2023-07-14 14:52 UTC, mhauru commented on docs/source/tutorials/airbnb.rst
> +After editing the ``config.yaml`` file, you can run: ::
I _think_ they might be equivalent, `code-block` just gives you the opportunity to specify the language to use for syntax highlighting purposes. Not confident in this claim though.

2023-07-14 14:55 UTC, cptanalatriste commented on pyproject.toml
> +pre-commit = {version = "^3.3.3", extras = ["dev"]}
Makes sense :)

2023-07-14 15:17 UTC, Olajumoke01 commented
> @Olajumoke01 is looking good: I just made some minor suggestions. Also, if you still have them, it would be nice to add the complete `config.yaml` and `airbnb_generators.py` files to the tutorial.

Hey Carlos, Do you mean add them near to the end of the tutorial as an example or as separate files somewhere?

2023-07-14 15:18 UTC, Olajumoke01 commented
> @Olajumoke01 is looking good: I just made some minor suggestions. Also, if you still have them, it would be nice to add the complete `config.yaml` and `airbnb_generators.py` files to the tutorial.

Hey @cptanalatrist, Do you mean add them near to the end of the tutorial as an example or as separate files somewhere?

2023-07-14 15:37 UTC, cptanalatriste commented
> > @Olajumoke01 is looking good: I just made some minor suggestions. Also, if you still have them, it would be nice to add the complete `config.yaml` and `airbnb_generators.py` files to the tutorial.
> 
> Hey @cptanalatrist, Do you mean add them near to the end of the tutorial as an example or as separate files somewhere?

Maybe you can add the files to the `airbnb` folder, and later add a paragraph at the end of the tutorial that goes: ``The complete files generated as part of this tutorial are available at [this location](htttp://your.link).

2023-07-17 12:16 UTC, cptanalatriste approved these changes
Looks good to me! Only a minor renaming request.

2023-07-19 11:50 UTC, Iain-S commented
only one thing:

- [ ] move pre-commit dep from an extra to the dev group

2023-07-20 16:08 UTC, merged