Adding the --force option to make-tables, make-generators, and make-stats
alan-turing-institute/sqlsynthgen pull request #81
Opened 2023-04-26 13:52 UTC by cptanalatriste

2023-04-26 16:16 UTC, mhauru requested changes
All the code looks really good. I've left one significant request of another change that I think should happen in the same PR, and one other tiny nit-picky point that's up for debate.

2023-04-26 16:16 UTC, mhauru commented on sqlsynthgen/main.py
> +    force: bool = typer.Option(False, "--force", "--f"),
For the short option, I would find it more intuitive if it was `-f` rather than `--f`.

2023-04-26 16:16 UTC, mhauru commented on sqlsynthgen/main.py
In addition to the ssg_file, make_generators may write .csv files for the vocabulary tables. To overwrite them too, the `force` option would need to be passed to `make_generators_from_tables`, and from there onwards to `sqlsynthgen.utils.download_table`. It's a bit unaesthetical, to have this argument just propagate it's way through a deep call stack, but I'm not sure we can easily avoid that. We could have `make_generators_from_tables` return the .csv files as text and write them to files here, but I wonder if this would cause trouble if the vocabulary tables are really big, big enough to use up significant memory.

2023-04-27 09:09 UTC, cptanalatriste commented on sqlsynthgen/main.py
> +    force: bool = typer.Option(False, "--force", "--f"),
Make sense! I'll make the change.

2023-04-27 09:11 UTC, cptanalatriste commented on sqlsynthgen/main.py
I see... I wasn't aware of the other CSV files. I'll come with a way of removing them too

2023-04-28 09:33 UTC, mhauru approved these changes
The code looks great, thanks Carlos! I'm confused by the diff, it seems to include some commits that are already in main, don't know why. As long as it merges fine though, :shrug:. Maybe merge main into this branch locally first (or rebase on main), see that it goes smoothly, then merge this into main?

2023-04-28 11:06 UTC, merged